### ISSUE TITLE
Yourls diverts me to install.php after pulling latest image from docker

### ISSUE THREAD

**Issue by Svampebob1** [YOURLS/images#214]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.2

### Description

Yourls sends me to the installation page /admin/install.php after pulling the latest image with Portainer.
This results me to have access to my short urls, but I'm unable to sign in. I loose everything, except for my username and password to the admin page, if I click "install YOURLS".

I use the example docker-compose.yml for yourls at hub.docker.com.

### Expectation

Settings should be kept after pulling the latest image.

### Reproduction steps

1. Log in to Portainer.
2. Go to the container.
3. Click recreate and select pulling the latest image.
4. You get the "Install YOURLS" message afterwards. Installation leads to the deletion of all short URLs.

### Context

I've tried setting up persistent storage on the container in the past. This lead to me being unable to update the docker image.

**Comment by LeoColomb** [comment]
Thanks for filing this issue, @Svampebob1.
Indeed, per default, a container data is not persistent and therefore lost when recreated. This is true for YOURLS configuration.
To keep the configuration, a volume must be created to store the config data into a persistent storage.
In our case, a volume on `/var/www/html/user/config.php`. In fact, it might be useful/simpler to mount the whole user folder, `/var/www/html/user`.

The update is blocked when the entire YOURLS location is mounted, `/var/www/html`, to avoid file mismatch. 

I'm closing the issue as answered, but don't hesitate to continue the discussion below is needed.

**Comment by Svampebob1** [comment]
I'm sorry, but I've lost all my short URLs again. I see that there has been an update two days ago.
I'm using watchtower for automatic updates. I've disabled this for this image, until I've found a solution.

What is the best practice on upgrading this image, without data?
I'm thinking about taking regular backups, so that I can restore when this happens the next time.
In case of backup restore, where is the short URLs stored?

**Comment by LeoColomb** [comment]
> What is the best practice on upgrading this image, without data?

First you must elaborate on which data you are talking about:
* As of your original report, you were talking about configuration data. The way to handle the configuration has been described in my previous answer.
* Now you are mentionning the lost of application data, i.e. actual links, which are stored on a external database. By external, it mease this database is independant of YOURLS, thus not affected by YOURLS updates.
  Please refer to this database documentation on how to handle it properly. If you are using MySQL, see its container usage documentation here: https://hub.docker.com/_/mysql

**Comment by Svampebob1** [comment]
Sorry. It was supposed to be "without loosing data". To be more specific: Without loosing my short URLs.

I've been using the example for docker compose from Docker hub. But I understand the problem now. I've been assuming that the short URLs has been stored as a file and logons has been stored in the database. But I see now that this is a completely wrong assumption.

Thanks for your help 👍️.

**Comment by Svampebob1** [comment]
To anyone else having the same issue, you can use the following Docker compose template for setting up Yourls:
version: '3.1'

services:

  yourls:
	image: yourls
	restart: always
	volumes:
	  - /<path-to-yourls>/yourls/user:/var/www/html/user   
	ports:
	  - 8083:80
	environment:
	  YOURLS_DB_PASS: <root DB password>
	  YOURLS_SITE: https://<url for yourls>
	  YOURLS_USER: <login user>
	  YOURLS_PASS: <login password>
	depends_on:
	  - mysql

  mysql:
	image: mysql
	restart: always
	environment:
	  MYSQL_ROOT_PASSWORD: <root DB password>
	  MYSQL_DATABASE: yourls
	volumes:
	  - /<path to yourls>/yourls/mysql-data:/var/lib/mysql
