### ISSUE TITLE
`fpm` image does not serve static files

### ISSUE THREAD

**Issue by eta-orionis** [YOURLS/images#243]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.2

### Description

Running latest yourls:fpm-alpine image with an nginx reverse proxy in front of it. 
jQuery and other static assets are "404 not found" by nginx -- which is to be expected, since they are not on the nginx container and the nginx container cannot access files on another container (yourls).
As a result, the interface simply does not work.

### Expectation

- The interface should work
- There should be a documented way how to configure reverse proxies in front of the fpm image

### Reproduction steps

docker-compose with three containers
- yourls:fpm-alpine
- mysql
- nginx

Configure yourls and nginx as per documentation at https://yourls.org/docs/guide/server-configuration#the-basic-nginx-server-configuration
Try accessing any of the static files, e.g. /js/jquery-3.5.1.min.js?v=1.9.2

### Context

The documentation does not provide any way or example to use the fpm image together with a reverse proxy. Such an example would be appreciated. If this is not possible at all, then the fpm image is of little use and could be deprecated/removed.

**Comment by LeoColomb** [comment]
Thanks for opening this issue @eta-orionis.
That said, I'm not sure to follow your point.
You are indeed free to use/build the infrastructure you want, and FPM images are an option that could match architecture needs.
But YOURLS documentation is focused on how to use YOURLS software, not really on how to design a complete service infra. Indeed, there is literally an infinite of possibilities.

Now in your specific case, if I understood correctly, you are using Nginx as a **reverse proxy** to handle FastCGI forwarding, which is great. 
That said, you are referring to the [Nginx **server** configuration template](https://yourls.org/docs/guide/server-configuration#the-basic-nginx-server-configuration), which is a different usage of Nginx. If you have used this configuration, static files won't be served, indeed.

I'd suggest two options:
* If you are skilled enough regarding Nginx proxying or if your provider offers technical support: Nginx can be tweaked to forward all requests with the correct criteria to YOURLS via Fast CGI protocol, static files included. It must be done according to your environment.
* If not: it's probably much easier to start with the default image, `latest` tag or `apache` tag, which comes with a ready to use HTTP-server.

**Comment by eta-orionis** [comment]
@LeoColomb thanks for your answer. We might be misunderstanding each other, so I'll try to explain in detail:

There is one nginx container in front of a yourls:fpm container. Nginx's job is to serve static assets and to pass requests for PHP files to php-fpm. (In YOURLS's [docker image documentation](https://hub.docker.com/_/yourls) this is called a "reverse proxy". It is the same thing that you mean with "server" in your comment. The template is also the most common configuration for such usage.)

> Nginx can be tweaked to forward all requests with the correct criteria to YOURLS via Fast CGI protocol, static files included.

Yes, but that's a **huge** security hole. Imagine passing a request for a GIF or CSS file to PHP, and imagine that the GIF or CSS contain the string `<?php include('https://rootkit.example.com'); ?>`

This leaves two options to serve static files:
1. serve static files via a PHP script (which your template does by redirecting requests to `/yourls-loader.php$is_args$args;`)
2. serve static files via nginx itself (which your template does with `try_files $uri $uri/ ...`)

Option 1 does not work, because `yourls-loader.php` is not written to serve static files. Execution falls through to line 68 and then instead of the requested static asset you get the homepage's HTML

Option 2 does not work because docker security does not allow the nginx container to access static files inside the yourls:fpm container. (There are workarounds, but the yourls:fpm image does not support those workarounds either).

Which means that:
1. either you know of a way to use the fpm image with nginx in front of it, but this way is not documented in the [image's documentation](https://hub.docker.com/_/yourls)
2. OR the yourls:fpm image, in its current state, can't be used with a webserver in front of it (which makes the yourls:fpm image useless)

> But YOURLS documentation is focused on how to use YOURLS software, not really on how to design a complete service infra.

Hence why I opened this issue on the YOURLS/**images** repo, referring to the *image* documentation


> it's probably much easier to start with the default image, latest tag or apache tag, which comes with a ready to use HTTP-server.

For a single service, yes. When running 20 public services, like I do, you don't want 20 copies of Apache running under docker. A single Nginx + 20 FPM containers are more than enough.

I sincerely hope that there is a way to use the fpm image with nginx in front of it, and that this is just a documentation issue.

Regards
